from django.urls import path
from app.schedule_check import views

app_name = 'schedule_check'
urlpatterns = [
    path('',
         views.IndexView.as_view(),
         name='index'),
    path('how_to_user/',
         views.HowToUserView.as_view(),
         name='how_to_user'),
    path('event/',
         views.EventListView.as_view(),
         name='event_list'),
    path('event/<int:event_id>',
         views.EventDetailListView.as_view(),
         name='event_list_detail'),
    path('event/create/',
         views.EventCreateView.as_view(),
         name='event_create'),
    path('event/edit/<int:event_id>',
         views.EventEditView.as_view(),
         name='event_edit'),
    path('event/delete/<int:event_id>',
         views.EventDeleteView.as_view(),
         name='event_delete'),
    path('event/password/<int:event_id>/<str:next_page>',
         views.EventPasswordAuth.as_view(),
         name='event_password'),
    path('event/event_url/<int:event_id>',
         views.EventUrlView.as_view(),
         name='event_url'),
    path('event/invite/<int:event_id>',
         views.InviteView.as_view(),
         name='invite'),
    path('event/attendance/<int:event_id>',
         views.AttendanceListView.as_view(),
         name='attendance'),
    path('event/attendance/<int:event_id>/edit/<int:invite_id>',
         views.AttendanceEditView.as_view(),
         name='attendance_edit'),
]
